[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/static_index.html"
  status = 200

[dev]
  command = "python -m http.server 8000"
  port = 8000
  publish = "." 